FROM php:8.2-fpm

RUN rm -rf /var/www/html

WORKDIR /var/www

RUN apt update && apt upgrade -y

RUN apt install libzip-dev libpq-dev -y

RUN apt install nodejs npm -y

RUN docker-php-ext-install zip \
                            pdo \
                            pdo_pgsql \
                            pgsql

RUN curl -s https://getcomposer.org/installer | php

RUN mv composer.phar /usr/local/bin/composer

RUN usermod -u 1000 www-data

RUN chown -R 1000:1000 /var/www

# Antes de fazer o primeiro build comentar a linha abaixo, entrar no container e rodar composer install
# Depois de gerar a vendor, descomentar a linha abaixo e rodar o build novamente
ENTRYPOINT [ "php", "/var/www/artisan", "serve", "--host=0.0.0.0", "--port=8000" ]

# CMD ["php-fpm"]

# EXPOSE 8000

# RUN composer create-project laravel/laravel /var/www/src
